version: '2'
services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "80:80"
    - "443:443"
    - "3128:3128"
    volumes:
    - ./:/usr/src/app/:rw
    # command: bash -c "sh ./start.sh"
    command: bash -c "sh ./sleep.sh"
    environment:
    - HELLO=WORLD
