version: '2'
services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "80:8888"
    volumes:
    - ./:/usr/src/app/:rw
    command: bash -c "sh ./start.sh"
    environment:
    - HELLO=WORLD
