version: '2'
services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
    - "80:80"
    - "443:443"
    - "3128:3128"
    volumes:
    - ./:/usr/src/app/:rw
    command: bash -c "make run"
    environment:
    - HELLO=WORLD
    # - RESTRICT_LOCAL=1
    # - DISABLE_TRANSPARENT_PROXY=1
