version: '2'
services:
  funes-test:
    build:
      context: ./
      dockerfile: Dockerfile.test
    ports:
    - "80:80"
    - "443:443"
    - "3128:3128"
    volumes:
    - ./:/usr/src/app/:rw
    privileged: true
    command: bash -c "make run & pip install -r test/requirements.txt && python -m unittest discover test"
